import {test} from 'node:test';
import assert from 'node:assert/strict';
import {blankProduct,calculate,fields,validateDB,createTemplate,applyTemplate} from '../calc.js';
function sample(){const p=blankProduct();for(const [k]of fields)p.values[k]=0;Object.assign(p.values,{grams:40,kgPrice:1500,minutes:80,yield:1,printerPrice:86000,printerLife:10000,watts:200,tariff:5,labor:2,maintenance:2,box:12,outer:25,capacity:2,labelPack:877,labelCount:7000,labels:1,outerLabels:1,bubblePrice:238,bubbleYield:100,card:2,buyout:90,volume:100});return p;}
test('known example including power and two packing capacities',()=>{const p=sample();assert.equal(calculate(p).cost.toFixed(2),'105.87');p.values.capacity=3;assert.equal(calculate(p).cost.toFixed(2),'101.68');});
test('tax on full sales price, target margin and break even',()=>{const p=sample();p.values.commission=37;p.price=300;const r=calculate(p);assert.ok(Math.abs(r.profit-(300*.59-r.fixed))<1e-9);p.price=r.min;assert.ok(Math.abs(calculate(p).profit)<1e-9);p.price=r.target;assert.ok(Math.abs(calculate(p).margin-30)<1e-9);});
test('unknowns flagged and 100% defect rejected',()=>{const p=sample();p.values.defect=null;assert.ok(calculate(p).missing.includes('defect'));p.values.defect=100;assert.ok(calculate(p).invalid.includes('defect'));});
test('buyout adds unsuccessful logistics without inflating all production',()=>{const p=sample();p.values.logistics=90;p.values.reverse=30;assert.ok(Math.abs(calculate(p).salesFixed-(90+3)/.9)<1e-9);});
test('zero buyout and invalid percentages rejected',()=>{const p=sample();p.values.buyout=0;assert.ok(calculate(p).invalid.includes('buyout'));});
test('unreachable target returns null',()=>{const p=sample();p.values.commission=70;p.target=30;assert.equal(calculate(p).target,null);});
test('additional fixed and percent expenses',()=>{const p=sample(),base=calculate(p);p.custom=[{id:'a',name:'Extra',amount:10,mode:'unit'},{id:'b',name:'Fee',amount:5,mode:'percent'}];const r=calculate(p);assert.equal(r.fixed,base.fixed+10);assert.ok(Math.abs(r.rate-base.rate-.05)<1e-9);});
test('base rejects incomplete and duplicate products before import',()=>{const p=sample();assert.throws(()=>validateDB({schema:2,products:[p]}));assert.throws(()=>validateDB({schema:1,id:'a',products:[p,p]}));assert.doesNotThrow(()=>validateDB({schema:1,id:'a',products:[p]}));p.values.grams=-1;assert.throws(()=>validateDB({schema:1,id:'a',products:[p]}));});
test('WB screenshot reconciles amounts and delivery is not divided by buyout again',()=>{const p=sample();Object.assign(p.values,{grams:0,kgPrice:0,printerPrice:0,watts:0,labor:0,maintenance:0,box:0,outer:0,labelPack:0,bubblePrice:0,card:0,otherUnit:110,commission:37,wbDelivery:95.35,logistics:999,reverse:999});p.shippingMode='wb-total';p.price=333;const r=calculate(p);assert.equal(r.platformFees.toFixed(2),'218.56');assert.equal(r.platformPayout.toFixed(2),'114.44');assert.equal(r.tax.toFixed(2),'13.32');assert.equal(r.totalExpenses.toFixed(2),'341.88');assert.equal(r.profit.toFixed(2),'-8.88');assert.equal(r.min.toFixed(2),'348.05');p.price=400;assert.equal(calculate(p).deliveryCost,95.35);});
test('legacy database migrates new delivery fields without changing expenses',()=>{const p=sample();delete p.shippingMode;delete p.values.wbDelivery;delete p.values.deliveryPercent;const db=validateDB({schema:1,id:'old',products:[p]});assert.equal(db.products[0].shippingMode,'rubles');assert.equal(db.products[0].values.wbDelivery,null);});
test('detailed expense table reconciles all totals across shipping modes',()=>{for(const mode of ['rubles','wb-total','percent']){const p=sample();p.shippingMode=mode;p.price=680;Object.assign(p.values,{commission:37,acquiring:1,ads:3,logistics:60,reverse:50,wbDelivery:95.35,deliveryPercent:14,loss:20,defect:5,rent:1000,otherUnit:2});p.custom=[{id:'a',name:'Custom fixed',mode:'unit',amount:7},{id:'b',name:'Custom percent',mode:'percent',amount:2}];const r=calculate(p);assert.ok(Math.abs(r.detailRows.reduce((sum,[,amount])=>sum+amount,0)-r.totalExpenses)<1e-8);assert.ok(Math.abs(p.price-r.totalExpenses-r.profit)<1e-8);}});

test('named templates persist and apply without changing product identity or history',()=>{const source=sample();source.price=680;const t=createTemplate(source,' PLA ');source.values.grams=99;const target=blankProduct();target.name='Target';target.sku='B';target.history=[{date:'saved'}];const q=applyTemplate(target,t);assert.equal(q.values.grams,40);assert.equal(q.name,'Target');assert.equal(q.sku,'B');assert.equal(q.id,target.id);assert.deepEqual(q.history,target.history);q.values.grams=50;assert.equal(t.inputs.values.grams,40);const db=validateDB(JSON.parse(JSON.stringify({schema:1,id:'a',products:[target],templates:[t]})));assert.equal(db.templates[0].name,'PLA');assert.equal(db.templates[0].inputs.price,680);assert.throws(()=>createTemplate(source,' '));assert.throws(()=>validateDB({schema:1,id:'a',products:[target],templates:[{id:'x',name:'x',inputs:{values:{}}}]}));});
